"""Initial schema

Revision ID: 7c1f4e7cd5e9
Revises: 
Create Date: 2026-06-12 10:20:36.401483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1f4e7cd5e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('banned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.Column('file_unique_id', sa.String(length=100), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('delete_token', sa.String(length=100), nullable=False),
    sa.Column('is_nsfw', sa.Boolean(), nullable=False),
    sa.Column('nsfw_checked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delete_token')
    )
    op.create_index(op.f('ix_images_created_at'), 'images', ['created_at'], unique=False)
    op.create_index(op.f('ix_images_file_unique_id'), 'images', ['file_unique_id'], unique=True)
    op.create_index(op.f('ix_images_slug'), 'images', ['slug'], unique=True)
    op.create_index(op.f('ix_images_uploaded_by'), 'images', ['uploaded_by'], unique=False)
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=False),
    sa.Column('referrer', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_image_id'), 'analytics', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_image_id'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_index(op.f('ix_images_uploaded_by'), table_name='images')
    op.drop_index(op.f('ix_images_slug'), table_name='images')
    op.drop_index(op.f('ix_images_file_unique_id'), table_name='images')
    op.drop_index(op.f('ix_images_created_at'), table_name='images')
    op.drop_table('images')
    op.drop_table('banned_users')
    # ### end Alembic commands ###
